import Footer from './components/Common/Footer';
import Navbar from './components/Common/Navbar';
import './globals.css';

interface Metadata {
  title: string;
  description: string;
}

interface RootLayoutProps {
  children: React.ReactNode;
}

const metadata: Metadata = {
  title: 'Lakshay Kamat | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
